/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TradeImport } from './routes/trade'
import { Route as StakeImport } from './routes/stake'
import { Route as DocsImport } from './routes/docs'
import { Route as CreateImport } from './routes/create'
import { Route as AssetsSelectorImport } from './routes/assetsSelector'
import { Route as IndexImport } from './routes/index'
import { Route as PortfolioIdImport } from './routes/portfolio/$id'
import { Route as ExploreIdImport } from './routes/explore/$id'

// Create/Update Routes

const TradeRoute = TradeImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRoute,
} as any)

const StakeRoute = StakeImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRoute,
} as any)

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const AssetsSelectorRoute = AssetsSelectorImport.update({
  id: '/assetsSelector',
  path: '/assetsSelector',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioIdRoute = PortfolioIdImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => rootRoute,
} as any)

const ExploreIdRoute = ExploreIdImport.update({
  id: '/explore/$id',
  path: '/explore/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/assetsSelector': {
      id: '/assetsSelector'
      path: '/assetsSelector'
      fullPath: '/assetsSelector'
      preLoaderRoute: typeof AssetsSelectorImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeImport
      parentRoute: typeof rootRoute
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeImport
      parentRoute: typeof rootRoute
    }
    '/explore/$id': {
      id: '/explore/$id'
      path: '/explore/$id'
      fullPath: '/explore/$id'
      preLoaderRoute: typeof ExploreIdImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assetsSelector': typeof AssetsSelectorRoute
  '/create': typeof CreateRoute
  '/docs': typeof DocsRoute
  '/stake': typeof StakeRoute
  '/trade': typeof TradeRoute
  '/explore/$id': typeof ExploreIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assetsSelector': typeof AssetsSelectorRoute
  '/create': typeof CreateRoute
  '/docs': typeof DocsRoute
  '/stake': typeof StakeRoute
  '/trade': typeof TradeRoute
  '/explore/$id': typeof ExploreIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/assetsSelector': typeof AssetsSelectorRoute
  '/create': typeof CreateRoute
  '/docs': typeof DocsRoute
  '/stake': typeof StakeRoute
  '/trade': typeof TradeRoute
  '/explore/$id': typeof ExploreIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assetsSelector'
    | '/create'
    | '/docs'
    | '/stake'
    | '/trade'
    | '/explore/$id'
    | '/portfolio/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assetsSelector'
    | '/create'
    | '/docs'
    | '/stake'
    | '/trade'
    | '/explore/$id'
    | '/portfolio/$id'
  id:
    | '__root__'
    | '/'
    | '/assetsSelector'
    | '/create'
    | '/docs'
    | '/stake'
    | '/trade'
    | '/explore/$id'
    | '/portfolio/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsSelectorRoute: typeof AssetsSelectorRoute
  CreateRoute: typeof CreateRoute
  DocsRoute: typeof DocsRoute
  StakeRoute: typeof StakeRoute
  TradeRoute: typeof TradeRoute
  ExploreIdRoute: typeof ExploreIdRoute
  PortfolioIdRoute: typeof PortfolioIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsSelectorRoute: AssetsSelectorRoute,
  CreateRoute: CreateRoute,
  DocsRoute: DocsRoute,
  StakeRoute: StakeRoute,
  TradeRoute: TradeRoute,
  ExploreIdRoute: ExploreIdRoute,
  PortfolioIdRoute: PortfolioIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/assetsSelector",
        "/create",
        "/docs",
        "/stake",
        "/trade",
        "/explore/$id",
        "/portfolio/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/assetsSelector": {
      "filePath": "assetsSelector.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/docs": {
      "filePath": "docs.tsx"
    },
    "/stake": {
      "filePath": "stake.tsx"
    },
    "/trade": {
      "filePath": "trade.tsx"
    },
    "/explore/$id": {
      "filePath": "explore/$id.tsx"
    },
    "/portfolio/$id": {
      "filePath": "portfolio/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
