# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: oven-sh/setup-bun@v2
#       with:
#         node-version: lts/*
#     - name: Install dependencies
#       run: bun i
#     - name: Install Playwright Browsers
#       run: bunx playwright install --with-deps
#     - name: Run Playwright tests
#       run: bunx playwright test
#     - uses: actions/upload-artifact@v4
#       if: ${{ !cancelled() }}
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
